"""added rank to users table

Revision ID: 048217f424a5
Revises: 4f0503aa5593
Create Date: 2022-06-29 09:06:50.048343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048217f424a5'
down_revision = '4f0503aa5593'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rank', sa.SMALLINT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rank')
    # ### end Alembic commands ###
