"""added event_codes table

Revision ID: 126cb69213b1
Revises: 4ab72236b10f
Create Date: 2022-07-06 12:43:46.885382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126cb69213b1'
down_revision = '4ab72236b10f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_codes',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=8), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_event_codes_code'), 'event_codes', ['code'], unique=False)
    op.create_index(op.f('ix_event_codes_event_id'), 'event_codes', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_codes_user_id'), 'event_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_codes_user_id'), table_name='event_codes')
    op.drop_index(op.f('ix_event_codes_event_id'), table_name='event_codes')
    op.drop_index(op.f('ix_event_codes_code'), table_name='event_codes')
    op.drop_table('event_codes')
    # ### end Alembic commands ###
