"""'rating_system'

Revision ID: 37ff82f5f82c
Revises: a33193b84343
Create Date: 2022-07-09 17:12:44.622094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ff82f5f82c'
down_revision = 'a33193b84343'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rating')
    # ### end Alembic commands ###
