"""ranem feedback tables

Revision ID: 4ab72236b10f
Revises: 55d9deea3cc3
Create Date: 2022-07-06 12:08:35.784481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab72236b10f'
down_revision = '55d9deea3cc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_editors',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_event_editors_event_id'), 'event_editors', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_editors_user_id'), 'event_editors', ['user_id'], unique=False)
    op.create_table('event_feedbacks',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('fb_text', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_event_feedbacks_event_id'), 'event_feedbacks', ['event_id'], unique=False)
    op.drop_index('ix_feedback_event_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_user-ev_event_id', table_name='user-ev')
    op.drop_index('ix_user-ev_user_id', table_name='user-ev')
    op.drop_table('user-ev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-ev',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_user-ev_user_id', 'user-ev', ['user_id'], unique=False)
    op.create_index('ix_user-ev_event_id', 'user-ev', ['event_id'], unique=False)
    op.create_table('feedback',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('fb_text', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_feedback_event_id', 'feedback', ['event_id'], unique=False)
    op.drop_index(op.f('ix_event_feedbacks_event_id'), table_name='event_feedbacks')
    op.drop_table('event_feedbacks')
    op.drop_index(op.f('ix_event_editors_user_id'), table_name='event_editors')
    op.drop_index(op.f('ix_event_editors_event_id'), table_name='event_editors')
    op.drop_table('event_editors')
    # ### end Alembic commands ###
