"""add_get_event_id_to_create_feedback

Revision ID: 55d9deea3cc3
Revises: 00c40a1011a9
Create Date: 2022-07-06 00:23:16.300061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d9deea3cc3'
down_revision = '00c40a1011a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-ev',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user-ev_event_id'), 'user-ev', ['event_id'], unique=False)
    op.create_index(op.f('ix_user-ev_user_id'), 'user-ev', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user-ev_user_id'), table_name='user-ev')
    op.drop_index(op.f('ix_user-ev_event_id'), table_name='user-ev')
    op.drop_table('user-ev')
    # ### end Alembic commands ###
