"""'create_editing_table'

Revision ID: 630a00f29309
Revises: d7cb2a2628fa
Create Date: 2022-07-09 22:22:06.375623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630a00f29309'
down_revision = 'd7cb2a2628fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
