"""'add_friend_request_status'

Revision ID: 7551be765176
Revises: 844be4048b87
Create Date: 2022-07-09 10:53:47.298242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7551be765176'
down_revision = '844be4048b87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_friends', sa.Column('friend_request_status', sa.Enum('ACCEPTED', 'WAITING', name='friendrequeststatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_friends', 'friend_request_status')
    # ### end Alembic commands ###
