"""added index to achievement table

Revision ID: 8823f9876d8b
Revises: 8ef90f1a9881
Create Date: 2022-07-09 17:05:06.015742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8823f9876d8b'
down_revision = '8ef90f1a9881'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_achievement_creator'), 'achievement', ['creator'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_achievement_creator'), table_name='achievement')
    # ### end Alembic commands ###
