"""added column coordinates to event table & remove columns desc and date in event table

Revision ID: 904bffbd0b91
Revises: 0410f803f03a
Create Date: 2022-06-30 19:17:40.379751

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '904bffbd0b91'
down_revision = '0410f803f03a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('event', sa.Column('lng', sa.Float(), nullable=True))
    op.drop_column('event', 'date')
    op.drop_column('event', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('description', sa.VARCHAR(length=255), nullable=False))
    op.add_column('event', sa.Column('date', sa.DATETIME(), nullable=False))
    op.drop_column('event', 'lng')
    op.drop_column('event', 'lat')
    # ### end Alembic commands ###
