"""added status_attendion column to event_users table

Revision ID: 913a7c87323a
Revises: c5580c6918fd
Create Date: 2022-07-05 12:38:02.397074

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '913a7c87323a'
down_revision = 'c5580c6918fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_users',
                  sa.Column('status_attendion', sa.Enum('ARRIVED', 'NOT_ARRIVED', name='statusattendion'),
                            nullable=True))
    op.create_index(op.f('ix_event_users_status_attendion'), 'event_users', ['status_attendion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_users_status_attendion'), table_name='event_users')
    op.drop_column('event_users', 'status_attendion')
    # ### end Alembic commands ###
