"""added status column to event table

Revision ID: 9219d8a9f6d5
Revises: 913a7c87323a
Create Date: 2022-07-05 13:00:50.525057

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9219d8a9f6d5'
down_revision = '913a7c87323a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('status', sa.Enum('UNFINISHED', 'FINISHED', name='statusevent'), nullable=False))  # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'status')  # ### end Alembic commands ###
