"""added editing table user achievements list

Revision ID: dce42c5cb937
Revises: d7cb2a2628fa
Create Date: 2022-07-10 01:44:55.089349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce42c5cb937'
down_revision = 'd7cb2a2628fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizer_to_user_achievement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_organizer_to_user_achievement_organizer_id'), 'organizer_to_user_achievement', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_organizer_to_user_achievement_user_id'), 'organizer_to_user_achievement', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizer_to_user_achievement_user_id'), table_name='organizer_to_user_achievement')
    op.drop_index(op.f('ix_organizer_to_user_achievement_organizer_id'), table_name='organizer_to_user_achievement')
    op.drop_table('organizer_to_user_achievement')
    # ### end Alembic commands ###
